/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rc.unesp.br.lcp.view;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import rc.unesp.br.lcp.beans.Produto;
import rc.unesp.br.lcp.dao.ProdutoEntity;

/**
 *
 * @author lfleming
 */
public class EditarProduto extends javax.swing.JInternalFrame {
  List<Produto> produtos = new ArrayList<>();
  /**
   * Creates new form EditarProduto
   */
  public EditarProduto() {
    initComponents();
    
    ProdutoEntity pe = new ProdutoEntity();
    produtos = pe.buscarTodos();
    
    for (Produto u : produtos) {
      jComboBox1.addItem(u.getNome());
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jComboBox1 = new javax.swing.JComboBox();

    setClosable(true);

    jButton1.setText("Editar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(49, 49, 49))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(53, 53, 53)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(44, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Produto p = produtos.get(jComboBox1.getSelectedIndex());
    cadastroProduto cp = new cadastroProduto(p);
    Dimension desktopSize = getParent().getSize();
    Dimension jInternalFrameSize = cp.getSize();
    cp.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);
    cp.setVisible(true);
    getParent().add(cp);
    cp.toFront();
    this.doDefaultCloseAction();
  }//GEN-LAST:event_jButton1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JComboBox jComboBox1;
  // End of variables declaration//GEN-END:variables
}
