/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rc.unesp.br.lcp.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rc.unesp.br.lcp.beans.Produto;
import rc.unesp.br.lcp.beans.Usuario;
import rc.unesp.br.lcp.beans.Venda;
import rc.unesp.br.lcp.beans.VendaProduto;
import rc.unesp.br.lcp.dao.UsuarioEntity;
import rc.unesp.br.lcp.dao.VendaEntity;

/**
 *
 * @author Matheus
 */
public class FormVenda extends javax.swing.JInternalFrame {

    private Venda venda = new Venda();
    
    /**
     * Creates new form FormVenda
     */
    public FormVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTable2 = new javax.swing.JTable();
    jButton3 = new javax.swing.JButton();

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jTable1);

    setClosable(true);

    jLabel2.setText("Cliente");

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel1.setText("Venda");

    jButton2.setText("Inserir Produto");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jButton1.setText("Procurar Cliente");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jTable2.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Produto", "Quantidade", "Valor"
      }
    )
    {public boolean isCellEditable(int row, int column){return false;}}
  );
  jScrollPane2.setViewportView(jTable2);

  jButton3.setText("Efetuar venda");
  jButton3.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      jButton3ActionPerformed(evt);
    }
  });

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
              .addGap(8, 8, 8)
              .addComponent(jLabel2)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
              .addGap(169, 169, 169)
              .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
              .addGap(139, 139, 139)
              .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGap(0, 0, Short.MAX_VALUE)))
      .addContainerGap())
    .addGroup(layout.createSequentialGroup()
      .addGap(142, 142, 142)
      .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );
  layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
      .addContainerGap()
      .addComponent(jLabel1)
      .addGap(18, 18, 18)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jLabel2)
        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGap(18, 18, 18)
      .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
      .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(20, 20, 20))
  );

  pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UsuarioEntity ue = new UsuarioEntity();
        Usuario cliente = ue.buscarPorNome(jTextField1.getText());
        
        if (cliente != null) {
          JOptionPane.showMessageDialog(rootPane, "Cliente " + cliente.getNome() + " selecionado", 
            "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
          venda.setCliente(cliente);
        } else {
          JOptionPane.showMessageDialog(rootPane, "Cliente não encontrado!",
            "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        InsercaoProduto ip = new InsercaoProduto(this);
        
        ip.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (venda.getProdutos() == null || venda.getCliente() == null) {
          JOptionPane.showMessageDialog(rootPane, 
      "Para efetuar a compra selecione um cliente e insira ao menos um produto!",
            "Erro!", JOptionPane.ERROR_MESSAGE);
        } else {
          VendaEntity ve = new VendaEntity();
          
          if(ve.inserir(venda) != null) {
            JOptionPane.showMessageDialog(rootPane, "Venda efetuada com sucesso.", 
            "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            
          } else {
            JOptionPane.showMessageDialog(rootPane, "Falha ao salvar! Por favor tente mais tarde!",
            "Erro!", JOptionPane.ERROR_MESSAGE);
          }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void inserirProduto(Produto produto, int qtd) {
      double valor = qtd * produto.getValor();
      VendaProduto vp = new VendaProduto();
      vp.setProduto(produto);
      vp.setQuantidade(qtd);
      vp.setValor(valor);
      venda.setProduto(vp);
      DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
      Object[] linha = new Object[]{produto.getNome(), 
                        qtd, valor};  
      modelo.addRow(linha);
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTable1;
  private javax.swing.JTable jTable2;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
