/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rc.unesp.br.lcp.view;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;

/**
 *
 * @author Unesp07
 */
public class formPrincipal extends javax.swing.JFrame {
    JDesktopPane jdDesktop;
    
    /**
     * Creates new form formPrincipal
     */
    public formPrincipal() {
        
        initComponents();
        setLayout(null);
        jdDesktop = new JDesktopPane();
        setContentPane(jdDesktop);
        jdDesktop.putClientProperty("JDesktopPane.dragMode", "outline");

        jdDesktop.add(jLabel1);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenu1 = new javax.swing.JMenu();
    jPopupMenu1 = new javax.swing.JPopupMenu();
    jMenuItem5 = new javax.swing.JMenuItem();
    jMenuBar2 = new javax.swing.JMenuBar();
    jMenu6 = new javax.swing.JMenu();
    jMenu7 = new javax.swing.JMenu();
    jMenuItem7 = new javax.swing.JMenuItem();
    jLabel1 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenuItem10 = new javax.swing.JMenuItem();
    jMenu3 = new javax.swing.JMenu();
    jMenuItem4 = new javax.swing.JMenuItem();
    jMenuItem9 = new javax.swing.JMenuItem();
    jMenu5 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenu4 = new javax.swing.JMenu();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenu9 = new javax.swing.JMenu();
    jMenuItem6 = new javax.swing.JMenuItem();
    jMenuItem8 = new javax.swing.JMenuItem();
    jMenu8 = new javax.swing.JMenu();

    jMenu1.setText("jMenu1");

    jMenuItem5.setText("jMenuItem5");

    jMenu6.setText("File");
    jMenuBar2.add(jMenu6);

    jMenu7.setText("Edit");
    jMenuBar2.add(jMenu7);

    jMenuItem7.setText("jMenuItem7");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(1062, 759));
    setResizable(false);

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supermercado.jpg"))); // NOI18N

    jMenu2.setText("Produto");

    jMenuItem3.setText("Cadastro");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem3ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem3);

    jMenuItem10.setText("Editar");
    jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem10ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem10);

    jMenuBar1.add(jMenu2);

    jMenu3.setText("Cliente");

    jMenuItem4.setText("Cadastro");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem4ActionPerformed(evt);
      }
    });
    jMenu3.add(jMenuItem4);

    jMenuItem9.setText("Editar");
    jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem9ActionPerformed(evt);
      }
    });
    jMenu3.add(jMenuItem9);

    jMenuBar1.add(jMenu3);

    jMenu5.setText("Admin");

    jMenuItem1.setText("Cadastro");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu5.add(jMenuItem1);

    jMenuBar1.add(jMenu5);

    jMenu4.setText("Venda");

    jMenuItem2.setText("Efetuar");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem2ActionPerformed(evt);
      }
    });
    jMenu4.add(jMenuItem2);

    jMenuBar1.add(jMenu4);

    jMenu9.setText("Relatórios");

    jMenuItem6.setText("Produtos");
    jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem6ActionPerformed(evt);
      }
    });
    jMenu9.add(jMenuItem6);

    jMenuItem8.setText("Clientes");
    jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem8ActionPerformed(evt);
      }
    });
    jMenu9.add(jMenuItem8);

    jMenuBar1.add(jMenu9);

    jMenu8.setLabel("Sair");
    jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jMenu8MouseClicked(evt);
      }
    });
    jMenu8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenu8ActionPerformed(evt);
      }
    });
    jMenuBar1.add(jMenu8);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(387, 387, 387)
        .addComponent(jLabel1)
        .addContainerGap(387, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(92, 92, 92)
        .addComponent(jLabel1)
        .addContainerGap(115, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        cadastroProduto cp = new cadastroProduto();
        Dimension desktopSize = jdDesktop.getSize();
        Dimension jInternalFrameSize = cp.getSize();
        cp.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);

        cp.setVisible(true);
        jdDesktop.add(cp);
        cp.toFront();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        cadastroCliente cc = new cadastroCliente();
        Dimension desktopSize = jdDesktop.getSize();
        Dimension jInternalFrameSize = cc.getSize();
        cc.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);

        cc.setVisible(true);
        jdDesktop.add(cc);
        cc.toFront();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        CadastroUsuario cadU = new CadastroUsuario();
        Dimension desktopSize = jdDesktop.getSize();
        Dimension jInternalFrameSize = cadU.getSize();
        cadU.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);

        cadU.setVisible(true);
        jdDesktop.add(cadU);
        cadU.toFront();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormVenda fv = new FormVenda();
        Dimension desktopSize = jdDesktop.getSize();
        Dimension jInternalFrameSize = fv.getSize();
        fv.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);

        fv.setVisible(true);
        jdDesktop.add(fv);
        fv.toFront();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

  private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
    
  }//GEN-LAST:event_jMenu8ActionPerformed

  private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
    this.setVisible(false);
    
    Application ap = new Application();
    ap.setVisible(true);
  }//GEN-LAST:event_jMenu8MouseClicked

  private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    RelatorioProdutos rp = new RelatorioProdutos();
    Dimension desktopSize = jdDesktop.getSize();
    Dimension jInternalFrameSize = rp.getSize();
    rp.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);

    rp.setVisible(true);
    jdDesktop.add(rp);
    rp.toFront();
  }//GEN-LAST:event_jMenuItem6ActionPerformed

  private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
    RelatorioVendasCliente rp = new RelatorioVendasCliente();
    Dimension desktopSize = jdDesktop.getSize();
    Dimension jInternalFrameSize = rp.getSize();
    rp.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);

    rp.setVisible(true);
    jdDesktop.add(rp);
    rp.toFront();
  }//GEN-LAST:event_jMenuItem8ActionPerformed

  private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
    EditarCliente ec = new EditarCliente();
    Dimension desktopSize = jdDesktop.getSize();
    Dimension jInternalFrameSize = ec.getSize();
    ec.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);

    ec.setVisible(true);
    jdDesktop.add(ec);
    ec.toFront();
  }//GEN-LAST:event_jMenuItem9ActionPerformed

  private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
    EditarProduto ec = new EditarProduto();
    Dimension desktopSize = jdDesktop.getSize();
    Dimension jInternalFrameSize = ec.getSize();
    ec.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);

    ec.setVisible(true);
    jdDesktop.add(ec);
    ec.toFront();
  }//GEN-LAST:event_jMenuItem10ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenu jMenu4;
  private javax.swing.JMenu jMenu5;
  private javax.swing.JMenu jMenu6;
  private javax.swing.JMenu jMenu7;
  private javax.swing.JMenu jMenu8;
  private javax.swing.JMenu jMenu9;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuBar jMenuBar2;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem10;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem6;
  private javax.swing.JMenuItem jMenuItem7;
  private javax.swing.JMenuItem jMenuItem8;
  private javax.swing.JMenuItem jMenuItem9;
  private javax.swing.JPopupMenu jPopupMenu1;
  // End of variables declaration//GEN-END:variables
}
